/**
 * Mobile Strategies
 *
 * Generates mobile app projects (React Native with Expo).
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Expo (React Native) mobile app strategy
 */
export const ExpoStrategy: GenerationStrategy = {
  id: 'mobile-expo',
  name: 'Expo Mobile App',
  priority: 10,

  matches: (stack) =>
    stack.archetype === 'mobile' && stack.framework === 'react-native',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();

    // 1. package.json
    files['package.json'] = JSON.stringify({
      name: cleanName,
      version: "1.0.0",
      main: "expo-router/entry",
      scripts: {
        "start": "expo start",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "web": "expo start --web",
        "lint": "eslint .",
        "test": "jest"
      },
      dependencies: {
        "expo": "~50.0.0",
        "expo-router": "~3.4.0",
        "expo-status-bar": "~1.11.1",
        "react": "18.2.0",
        "react-native": "0.73.2",
        "react-native-safe-area-context": "4.8.2",
        "react-native-screens": "~3.29.0"
      },
      devDependencies: {
        "@babel/core": "^7.20.0",
        "@types/react": "~18.2.45",
        "eslint": "^8.56.0",
        "eslint-config-expo": "^7.0.0",
        "jest": "^29.7.0",
        "jest-expo": "~50.0.0",
        "typescript": "^5.3.0"
      },
      jest: {
        preset: "jest-expo"
      }
    }, null, 2);

    // 2. app.json
    files['app.json'] = JSON.stringify({
      expo: {
        name: projectName,
        slug: cleanName,
        version: "1.0.0",
        orientation: "portrait",
        icon: "./assets/icon.png",
        scheme: cleanName,
        userInterfaceStyle: "automatic",
        splash: {
          image: "./assets/splash.png",
          resizeMode: "contain",
          backgroundColor: "#ffffff"
        },
        ios: {
          supportsTablet: true,
          bundleIdentifier: `com.example.${cleanName}`
        },
        android: {
          adaptiveIcon: {
            foregroundImage: "./assets/adaptive-icon.png",
            backgroundColor: "#ffffff"
          },
          package: `com.example.${cleanName}`
        },
        web: {
          bundler: "metro",
          output: "static",
          favicon: "./assets/favicon.png"
        },
        plugins: ["expo-router"]
      }
    }, null, 2);

    // 3. Babel Config
    files['babel.config.js'] = `module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};
`;

    // 4. TypeScript Config
    files['tsconfig.json'] = JSON.stringify({
      extends: "expo/tsconfig.base",
      compilerOptions: {
        strict: true,
        baseUrl: ".",
        paths: {
          "@/*": ["./*"]
        }
      },
      include: ["**/*.ts", "**/*.tsx", ".expo/types/**/*.ts", "expo-env.d.ts"]
    }, null, 2);

    // 5. ESLint Config
    files['.eslintrc.js'] = `module.exports = {
  extends: 'expo',
  rules: {
    // Add custom rules here
  },
};
`;

    // 6. App Layout
    files['app/_layout.tsx'] = `import { Stack } from 'expo-router';

export default function Layout() {
  return (
    <Stack>
      <Stack.Screen name="index" options={{ title: 'Home' }} />
      <Stack.Screen name="about" options={{ title: 'About' }} />
    </Stack>
  );
}
`;

    // 7. Home Screen
    files['app/index.tsx'] = `import { StyleSheet, Text, View, Pressable } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Link } from 'expo-router';

export default function HomeScreen() {
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Welcome to ${projectName}!</Text>
      <Text style={styles.subtitle}>Generated by Retro Vibecoder UPG</Text>

      <Link href="/about" asChild>
        <Pressable style={styles.button}>
          <Text style={styles.buttonText}>Learn More</Text>
        </Pressable>
      </Link>

      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    marginBottom: 30,
  },
  button: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
`;

    // 8. About Screen
    files['app/about.tsx'] = `import { StyleSheet, Text, View, ScrollView } from 'react-native';

export default function AboutScreen() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>About ${projectName}</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Built With</Text>
        <Text style={styles.text}>React Native + Expo</Text>
        <Text style={styles.text}>Expo Router for navigation</Text>
        <Text style={styles.text}>TypeScript for type safety</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Getting Started</Text>
        <Text style={styles.text}>1. Run 'npm start' or 'yarn start'</Text>
        <Text style={styles.text}>2. Scan QR code with Expo Go app</Text>
        <Text style={styles.text}>3. Start building your app!</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 24,
    textAlign: 'center',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 12,
    color: '#333',
  },
  text: {
    fontSize: 16,
    color: '#666',
    marginBottom: 8,
    lineHeight: 24,
  },
});
`;

    // 9. Basic test
    files['__tests__/App.test.tsx'] = `import { render } from '@testing-library/react-native';

// Note: Tests would need proper setup with expo-router mocking
describe('App', () => {
  it('should pass basic test', () => {
    expect(true).toBe(true);
  });
});
`;

    // 10. .gitignore
    files['.gitignore'] = `# Dependencies
node_modules/

# Expo
.expo/
dist/
web-build/

# Native
*.orig.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision

# Metro
.metro-health-check*

# Debug
npm-debug.*
yarn-debug.*
yarn-error.*

# macOS
.DS_Store
*.pem

# Local env files
.env*.local
.env

# TypeScript
*.tsbuildinfo

# Testing
coverage/
`;

    // 11. Assets placeholder files
    files['assets/.gitkeep'] = '# Placeholder for asset files (icon.png, splash.png, etc.)\n';

    // 12. README
    files['README.md'] = `# ${projectName}

A mobile app built with React Native and Expo.

## Getting Started

### Prerequisites

- Node.js 18+
- npm or yarn
- Expo Go app on your mobile device

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
# Start the development server
npm start

# Run on iOS simulator
npm run ios

# Run on Android emulator
npm run android

# Run in web browser
npm run web
\`\`\`

## Project Structure

\`\`\`
app/                  # File-based routing (Expo Router)
  _layout.tsx         # Root layout
  index.tsx           # Home screen
  about.tsx           # About screen
assets/               # Images and fonts
__tests__/            # Test files
\`\`\`

## Built With

- [Expo](https://expo.dev/) - Development platform
- [React Native](https://reactnative.dev/) - Mobile framework
- [Expo Router](https://docs.expo.dev/router/introduction/) - File-based routing
- [TypeScript](https://www.typescriptlang.org/) - Type safety
`;
  },
};
