/**
 * C# Game Strategies
 *
 * Generates game projects using Unity and Godot Mono.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Unity game strategy
 */
export const UnityStrategy: GenerationStrategy = {
  id: 'game-unity',
  name: 'Unity Game',
  priority: 10,

  matches: stack => stack.archetype === 'game' && stack.framework === 'unity',

  apply: async ({ files, projectName }) => {
    const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');

    // Assembly definition
    files['Assembly-CSharp.csproj'] = `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
  </PropertyGroup>
</Project>
`;

    // Packages manifest
    files['Packages/manifest.json'] = JSON.stringify(
      {
        dependencies: {
          'com.unity.2d.sprite': '1.0.0',
          'com.unity.inputsystem': '1.7.0',
          'com.unity.textmeshpro': '3.0.6',
          'com.unity.ugui': '1.0.0',
          'com.unity.modules.physics2d': '1.0.0',
        },
      },
      null,
      2
    );

    // GameManager
    files['Assets/Scripts/GameManager.cs'] = `using UnityEngine;

namespace ${safeName}
{
    /// <summary>
    /// Central game manager — singleton pattern.
    /// </summary>
    public class GameManager : MonoBehaviour
    {
        public static GameManager Instance { get; private set; }

        [SerializeField] private int score;

        public int Score => score;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }

        public void AddScore(int points)
        {
            score += points;
            Debug.Log($"Score: {score}");
        }

        public void ResetGame()
        {
            score = 0;
        }
    }
}
`;

    // PlayerController
    files['Assets/Scripts/PlayerController.cs'] = `using UnityEngine;

namespace ${safeName}
{
    /// <summary>
    /// Basic player controller with movement.
    /// </summary>
    public class PlayerController : MonoBehaviour
    {
        [SerializeField] private float moveSpeed = 5f;

        private Rigidbody2D rb;
        private Vector2 movement;

        private void Awake()
        {
            rb = GetComponent<Rigidbody2D>();
        }

        private void Update()
        {
            movement.x = Input.GetAxisRaw("Horizontal");
            movement.y = Input.GetAxisRaw("Vertical");
        }

        private void FixedUpdate()
        {
            rb.MovePosition(rb.position + movement * moveSpeed * Time.fixedDeltaTime);
        }
    }
}
`;

    // UIManager
    files['Assets/Scripts/UIManager.cs'] = `using UnityEngine;
using UnityEngine.UI;

namespace ${safeName}
{
    /// <summary>
    /// Manages the game UI.
    /// </summary>
    public class UIManager : MonoBehaviour
    {
        [SerializeField] private Text scoreText;

        private void Update()
        {
            if (GameManager.Instance != null && scoreText != null)
            {
                scoreText.text = $"Score: {GameManager.Instance.Score}";
            }
        }
    }
}
`;

    // Scene placeholder
    files['Assets/Scenes/MainScene.unity.meta'] = `fileFormatVersion: 2
guid: 00000000000000000000000000000001
`;

    // ProjectSettings
    files['ProjectSettings/ProjectSettings.asset'] = `%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!129 &1
PlayerSettings:
  productName: ${projectName}
  companyName: Example
  defaultScreenWidth: 1920
  defaultScreenHeight: 1080
`;

    // .gitignore
    files['.gitignore'] = `# Unity
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Mm]emoryCaptures/
[Uu]serSettings/

*.csproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

*.pidb.meta
*.pdb.meta
*.mdb.meta

sysinfo.txt
crashlytics-build.properties

# OS
.DS_Store
Thumbs.db
`;

    // Makefile
    files['Makefile'] = `.PHONY: build test clean

build:
\t@echo "Open the project in Unity Editor to build"

test:
\t@echo "Run tests via Unity Test Runner"

clean:
\trm -rf Library/ Temp/ Obj/ Build/ Logs/
`;
  },
};

/**
 * Godot Mono game strategy
 */
export const GodotMonoStrategy: GenerationStrategy = {
  id: 'game-godot-mono',
  name: 'Godot Mono Game',
  priority: 10,

  matches: stack => stack.archetype === 'game' && stack.framework === 'godot-mono',

  apply: async ({ files, projectName }) => {
    const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');

    // project.godot
    files['project.godot'] = `; Engine configuration file.
; Generated by Retro Vibecoder UPG.

[application]

config/name="${projectName}"
run/main_scene="res://Scenes/Main.tscn"
config/features=PackedStringArray("4.2", "C#", "Mobile")

[dotnet]

project/assembly_name="${safeName}"
`;

    // .csproj
    files[`${safeName}.csproj`] = `<Project Sdk="Godot.NET.Sdk/4.2.0">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
</Project>
`;

    // .sln
    files[`${safeName}.sln`] = `
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "${safeName}", "${safeName}.csproj", "{00000000-0000-0000-0000-000000000001}"
EndProject
Global
  GlobalSection(SolutionConfigurationPlatforms) = preSolution
    Debug|Any CPU = Debug|Any CPU
    Release|Any CPU = Release|Any CPU
  EndGlobalSection
EndGlobal
`;

    // Main scene script
    files['Scripts/Main.cs'] = `using Godot;

namespace ${safeName};

/// <summary>
/// Main scene controller.
/// </summary>
public partial class Main : Node
{
    private int _score;
    private Label _scoreLabel;

    public override void _Ready()
    {
        _scoreLabel = GetNodeOrNull<Label>("UI/ScoreLabel");
        GD.Print("${projectName} started!");
    }

    public override void _Process(double delta)
    {
        // Game loop logic
    }

    public void AddScore(int points)
    {
        _score += points;
        if (_scoreLabel != null)
        {
            _scoreLabel.Text = $"Score: {_score}";
        }
    }
}
`;

    // Player script
    files['Scripts/Player.cs'] = `using Godot;

namespace ${safeName};

/// <summary>
/// Player character controller.
/// </summary>
public partial class Player : CharacterBody2D
{
    [Export] public float Speed { get; set; } = 200.0f;

    public override void _PhysicsProcess(double delta)
    {
        var velocity = Vector2.Zero;

        if (Input.IsActionPressed("ui_right"))
            velocity.X += 1;
        if (Input.IsActionPressed("ui_left"))
            velocity.X -= 1;
        if (Input.IsActionPressed("ui_down"))
            velocity.Y += 1;
        if (Input.IsActionPressed("ui_up"))
            velocity.Y -= 1;

        if (velocity.Length() > 0)
        {
            velocity = velocity.Normalized() * Speed;
        }

        Velocity = velocity;
        MoveAndSlide();
    }
}
`;

    // GameManager
    files['Scripts/GameManager.cs'] = `using Godot;

namespace ${safeName};

/// <summary>
/// Autoloaded game manager.
/// </summary>
public partial class GameManager : Node
{
    public static GameManager Instance { get; private set; }

    public int Score { get; private set; }

    public override void _Ready()
    {
        Instance = this;
    }

    public void AddScore(int points)
    {
        Score += points;
    }

    public void ResetGame()
    {
        Score = 0;
    }
}
`;

    // Main scene file
    files['Scenes/Main.tscn'] = `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://Scripts/Main.cs" id="1"]

[node name="Main" type="Node"]
script = ExtResource("1")

[node name="UI" type="CanvasLayer" parent="."]

[node name="ScoreLabel" type="Label" parent="UI"]
offset_right = 200.0
offset_bottom = 40.0
text = "Score: 0"
`;

    // .gitignore
    files['.gitignore'] = `# Godot
.godot/
.import/

# .NET
bin/
obj/
*.user

# OS
.DS_Store
Thumbs.db
`;

    // Makefile
    files['Makefile'] = `DOTNET := dotnet

.PHONY: build test clean

build:
\t$(DOTNET) build

test:
\t@echo "Run tests via Godot editor or dotnet test"

clean:
\t$(DOTNET) clean
\trm -rf .godot/
`;
  },
};
