/**
 * TypeScript Game Strategies
 *
 * Generates game projects using Phaser and PixiJS.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Phaser game strategy
 */
export const PhaserStrategy: GenerationStrategy = {
  id: 'game-phaser',
  name: 'Phaser Game',
  priority: 10,

  matches: stack => stack.archetype === 'game' && stack.framework === 'phaser',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();

    // package.json
    files['package.json'] = JSON.stringify(
      {
        name: cleanName,
        version: '0.1.0',
        description: `${projectName} - A Phaser game`,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
        },
        dependencies: {
          phaser: '^3.80.0',
        },
        devDependencies: {
          typescript: '^5.3.0',
          vite: '^5.1.0',
          vitest: '^1.2.0',
        },
      },
      null,
      2
    );

    // tsconfig.json
    files['tsconfig.json'] = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: 'dist',
        },
        include: ['src'],
      },
      null,
      2
    );

    // vite.config.ts
    files['vite.config.ts'] = `import { defineConfig } from 'vite';

export default defineConfig({
  base: './',
  build: {
    outDir: 'dist',
  },
});
`;

    // config.ts
    files['src/config.ts'] = `import Phaser from 'phaser';
import { BootScene } from './scenes/BootScene';
import { PreloadScene } from './scenes/PreloadScene';
import { GameScene } from './scenes/GameScene';

export const GAME_WIDTH = 800;
export const GAME_HEIGHT = 600;

export const gameConfig: Phaser.Types.Core.GameConfig = {
  type: Phaser.AUTO,
  width: GAME_WIDTH,
  height: GAME_HEIGHT,
  parent: 'game-container',
  backgroundColor: '#1a1a2e',
  physics: {
    default: 'arcade',
    arcade: {
      gravity: { x: 0, y: 300 },
      debug: false,
    },
  },
  scene: [BootScene, PreloadScene, GameScene],
};
`;

    // main.ts
    files['src/main.ts'] = `import Phaser from 'phaser';
import { gameConfig } from './config';

new Phaser.Game(gameConfig);
`;

    // BootScene
    files['src/scenes/BootScene.ts'] = `import Phaser from 'phaser';

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: 'BootScene' });
  }

  preload(): void {
    // Load minimal assets needed for the preload screen
  }

  create(): void {
    this.scene.start('PreloadScene');
  }
}
`;

    // PreloadScene
    files['src/scenes/PreloadScene.ts'] = `import Phaser from 'phaser';

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreloadScene' });
  }

  preload(): void {
    // Show loading bar
    const width = this.cameras.main.width;
    const height = this.cameras.main.height;

    const progressBar = this.add.graphics();
    const progressBox = this.add.graphics();
    progressBox.fillStyle(0x222222, 0.8);
    progressBox.fillRect(width / 2 - 160, height / 2 - 25, 320, 50);

    this.load.on('progress', (value: number) => {
      progressBar.clear();
      progressBar.fillStyle(0x00ff88, 1);
      progressBar.fillRect(width / 2 - 150, height / 2 - 15, 300 * value, 30);
    });

    this.load.on('complete', () => {
      progressBar.destroy();
      progressBox.destroy();
    });

    // Load game assets here
    // this.load.image('player', 'assets/player.png');
  }

  create(): void {
    this.scene.start('GameScene');
  }
}
`;

    // GameScene
    files['src/scenes/GameScene.ts'] = `import Phaser from 'phaser';
import { GAME_WIDTH, GAME_HEIGHT } from '../config';

export class GameScene extends Phaser.Scene {
  private score = 0;
  private scoreText!: Phaser.GameObjects.Text;

  constructor() {
    super({ key: 'GameScene' });
  }

  create(): void {
    // Title
    this.add
      .text(GAME_WIDTH / 2, 50, '${projectName}', {
        fontSize: '32px',
        color: '#00ff88',
      })
      .setOrigin(0.5);

    // Subtitle
    this.add
      .text(GAME_WIDTH / 2, 90, 'Generated by Retro Vibecoder UPG', {
        fontSize: '16px',
        color: '#888888',
      })
      .setOrigin(0.5);

    // Score
    this.scoreText = this.add.text(16, 16, 'Score: 0', {
      fontSize: '20px',
      color: '#ffffff',
    });

    // Instructions
    this.add
      .text(GAME_WIDTH / 2, GAME_HEIGHT - 50, 'Click to add score!', {
        fontSize: '18px',
        color: '#aaaaaa',
      })
      .setOrigin(0.5);

    // Input
    this.input.on('pointerdown', () => {
      this.score += 10;
      this.scoreText.setText('Score: ' + this.score);
    });
  }

  update(): void {
    // Game loop logic goes here
  }
}
`;

    // index.html
    files['public/index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName}</title>
  <style>
    body { margin: 0; background: #0a0a1a; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
  </style>
</head>
<body>
  <div id="game-container"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
`;

    // assets placeholder
    files['public/assets/.gitkeep'] = '';

    // .gitignore
    files['.gitignore'] = `node_modules/
dist/
*.tsbuildinfo
`;

    // Makefile
    files['Makefile'] = `NPM := npm

.PHONY: dev build test clean

dev:
\t$(NPM) run dev

build:
\t$(NPM) run build

test:
\t$(NPM) test

clean:
\trm -rf dist node_modules
`;
  },
};

/**
 * PixiJS game strategy
 */
export const PixiJSStrategy: GenerationStrategy = {
  id: 'game-pixijs',
  name: 'PixiJS Game',
  priority: 10,

  matches: stack => stack.archetype === 'game' && stack.framework === 'pixijs',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();

    // package.json
    files['package.json'] = JSON.stringify(
      {
        name: cleanName,
        version: '0.1.0',
        description: `${projectName} - A PixiJS game`,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
        },
        dependencies: {
          pixi: '^8.0.0',
        },
        devDependencies: {
          typescript: '^5.3.0',
          vite: '^5.1.0',
          vitest: '^1.2.0',
        },
      },
      null,
      2
    );

    // tsconfig.json
    files['tsconfig.json'] = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: 'dist',
        },
        include: ['src'],
      },
      null,
      2
    );

    // vite.config.ts
    files['vite.config.ts'] = `import { defineConfig } from 'vite';

export default defineConfig({
  base: './',
  build: {
    outDir: 'dist',
  },
});
`;

    // main.ts
    files['src/main.ts'] = `import { Application, Text } from 'pixi.js';

async function init(): Promise<void> {
  const app = new Application();
  await app.init({
    width: 800,
    height: 600,
    backgroundColor: 0x1a1a2e,
  });

  document.getElementById('game-container')?.appendChild(app.canvas);

  // Title
  const title = new Text({
    text: '${projectName}',
    style: { fontSize: 32, fill: 0x00ff88 },
  });
  title.anchor.set(0.5);
  title.x = app.screen.width / 2;
  title.y = 50;
  app.stage.addChild(title);

  // Subtitle
  const subtitle = new Text({
    text: 'Generated by Retro Vibecoder UPG',
    style: { fontSize: 16, fill: 0x888888 },
  });
  subtitle.anchor.set(0.5);
  subtitle.x = app.screen.width / 2;
  subtitle.y = 90;
  app.stage.addChild(subtitle);

  // Game loop
  app.ticker.add((ticker) => {
    // Update logic goes here
    title.rotation += 0.001 * ticker.deltaTime;
  });
}

init();
`;

    // GameScene
    files['src/scenes/GameScene.ts'] = `import { Container, Text } from 'pixi.js';

export class GameScene extends Container {
  private score = 0;
  private scoreText: Text;

  constructor() {
    super();

    this.scoreText = new Text({
      text: 'Score: 0',
      style: { fontSize: 20, fill: 0xffffff },
    });
    this.scoreText.x = 16;
    this.scoreText.y = 16;
    this.addChild(this.scoreText);

    this.eventMode = 'static';
    this.on('pointerdown', () => {
      this.score += 10;
      this.scoreText.text = 'Score: ' + this.score;
    });
  }

  update(delta: number): void {
    // Scene update logic
    void delta;
  }
}
`;

    // Player sprite
    files['src/sprites/Player.ts'] = `import { Sprite, Texture } from 'pixi.js';

export class Player extends Sprite {
  private speed = 5;

  constructor(texture?: Texture) {
    super(texture);
    this.anchor.set(0.5);
  }

  moveLeft(): void {
    this.x -= this.speed;
  }

  moveRight(): void {
    this.x += this.speed;
  }

  moveUp(): void {
    this.y -= this.speed;
  }

  moveDown(): void {
    this.y += this.speed;
  }
}
`;

    // index.html
    files['public/index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName}</title>
  <style>
    body { margin: 0; background: #0a0a1a; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
  </style>
</head>
<body>
  <div id="game-container"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
`;

    // .gitignore
    files['.gitignore'] = `node_modules/
dist/
*.tsbuildinfo
`;

    // Makefile
    files['Makefile'] = `NPM := npm

.PHONY: dev build test clean

dev:
\t$(NPM) run dev

build:
\t$(NPM) run build

test:
\t$(NPM) test

clean:
\trm -rf dist node_modules
`;
  },
};
