/**
 * Electron Desktop Strategy
 *
 * Generates Electron desktop applications with TypeScript.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Electron desktop app strategy
 */
export const ElectronStrategy: GenerationStrategy = {
  id: 'desktop-electron',
  name: 'Electron Desktop App',
  priority: 10,

  matches: stack =>
    stack.archetype === 'desktop' &&
    (stack.language === 'typescript' || stack.language === 'javascript') &&
    stack.framework === 'electron',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();

    // 1. package.json
    files['package.json'] = JSON.stringify(
      {
        name: cleanName,
        version: '0.1.0',
        description: `${projectName} - Electron desktop app`,
        main: 'dist/main.js',
        scripts: {
          build: 'tsup',
          start: 'electron .',
          dev: 'tsup --watch & electron .',
          test: 'vitest run',
          'test:watch': 'vitest',
          lint: 'eslint src/',
          package: 'electron-builder',
          'package:mac': 'electron-builder --mac',
          'package:win': 'electron-builder --win',
          'package:linux': 'electron-builder --linux',
        },
        dependencies: {
          electron: '^28.0.0',
        },
        devDependencies: {
          '@types/node': '^20.11.0',
          'electron-builder': '^24.9.0',
          tsup: '^8.0.0',
          typescript: '^5.3.0',
          vitest: '^1.2.0',
        },
      },
      null,
      2
    );

    // 2. tsconfig.json
    files['tsconfig.json'] = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'CommonJS',
          moduleResolution: 'node',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: 'dist',
          rootDir: 'src',
          declaration: true,
          sourceMap: true,
        },
        include: ['src'],
        exclude: ['node_modules', 'dist'],
      },
      null,
      2
    );

    // 3. tsup.config.ts
    files['tsup.config.ts'] = `import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    main: 'src/main.ts',
    preload: 'src/preload.ts',
  },
  format: ['cjs'],
  clean: true,
  sourcemap: true,
  external: ['electron'],
});
`;

    // 4. Main process
    files['src/main.ts'] = `import { app, BrowserWindow } from 'electron';
import * as path from 'path';

function createWindow(): void {
  const mainWindow = new BrowserWindow({
    width: 900,
    height: 670,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow.loadFile(path.join(__dirname, '../src/renderer/index.html'));

  if (process.env.NODE_ENV === 'development') {
    mainWindow.webContents.openDevTools();
  }
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
`;

    // 5. Preload
    files['src/preload.ts'] = `import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('api', {
  getVersion: (): Promise<string> => ipcRenderer.invoke('get-version'),
  platform: process.platform,
});
`;

    // 6. Renderer HTML
    files['src/renderer/index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'" />
  <title>${projectName}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <div id="app">
    <h1>Welcome to ${projectName}!</h1>
    <p>Generated by Retro Vibecoder UPG</p>
    <p id="platform"></p>
  </div>
  <script src="app.js"></script>
</body>
</html>
`;

    // 7. Renderer JS
    files['src/renderer/app.js'] = `document.addEventListener('DOMContentLoaded', () => {
  const platformEl = document.getElementById('platform');
  if (platformEl && window.api) {
    platformEl.textContent = 'Running on: ' + window.api.platform;
  }
});
`;

    // 8. Renderer CSS
    files['src/renderer/styles.css'] = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background-color: #1e1e2e;
  color: #cdd6f4;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

#app {
  text-align: center;
  padding: 2rem;
}

h1 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
  color: #cba6f7;
}

p {
  color: #a6adc8;
  margin-bottom: 0.5rem;
}
`;

    // 9. electron-builder config
    files['electron-builder.yml'] = `appId: com.example.${cleanName}
productName: ${projectName}
directories:
  output: release
files:
  - dist/**/*
  - src/renderer/**/*
mac:
  target: dmg
win:
  target: nsis
linux:
  target: AppImage
`;

    // 10. Test
    files['src/__tests__/app.test.ts'] = `import { describe, it, expect } from 'vitest';

describe('${projectName}', () => {
  it('should pass basic test', () => {
    expect(true).toBe(true);
  });
});
`;

    // 11. .gitignore
    files['.gitignore'] = `node_modules/
dist/
release/
*.tsbuildinfo
.env
.env.local
`;

    // 12. Makefile
    files['Makefile'] = `NPM := npm

.PHONY: build start dev test lint package clean

build:
\t$(NPM) run build

start:
\t$(NPM) start

dev:
\t$(NPM) run dev

test:
\t$(NPM) test

lint:
\t$(NPM) run lint

package:
\t$(NPM) run package

clean:
\trm -rf dist release node_modules
`;
  },
};
