/**
 * Flutter Desktop Strategy
 *
 * Generates Flutter desktop/mobile applications.
 * Matches both desktop and mobile archetypes when Flutter is selected.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Flutter strategy (desktop and mobile)
 */
export const FlutterStrategy: GenerationStrategy = {
  id: 'desktop-flutter',
  name: 'Flutter App',
  priority: 10,

  matches: stack =>
    (stack.archetype === 'desktop' || stack.archetype === 'mobile') &&
    stack.framework === 'flutter',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase();

    // 1. pubspec.yaml
    files['pubspec.yaml'] = `name: ${cleanName}
description: ${projectName} - A Flutter application.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
`;

    // 2. analysis_options.yaml
    files['analysis_options.yaml'] = `include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
`;

    // 3. lib/main.dart
    files['lib/main.dart'] = `import 'package:flutter/material.dart';
import 'screens/home_screen.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${projectName}',
      theme: ThemeData(
        colorSchemeSeed: Colors.deepPurple,
        useMaterial3: true,
        brightness: Brightness.light,
      ),
      darkTheme: ThemeData(
        colorSchemeSeed: Colors.deepPurple,
        useMaterial3: true,
        brightness: Brightness.dark,
      ),
      themeMode: ThemeMode.system,
      home: const HomeScreen(),
    );
  }
}
`;

    // 4. lib/screens/home_screen.dart
    files['lib/screens/home_screen.dart'] = `import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('${projectName}'),
        centerTitle: true,
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(
              'Welcome to ${projectName}!',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 8),
            Text(
              'Generated by Retro Vibecoder UPG',
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: Theme.of(context).colorScheme.onSurfaceVariant,
                  ),
            ),
            const SizedBox(height: 32),
            Text(
              'Counter: $_counter',
              style: Theme.of(context).textTheme.titleLarge,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
`;

    // 5. test/widget_test.dart
    files['test/widget_test.dart'] = `import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:${cleanName}/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());

    expect(find.text('Counter: 0'), findsOneWidget);

    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    expect(find.text('Counter: 1'), findsOneWidget);
  });
}
`;

    // 6. .gitignore
    files['.gitignore'] = `# Flutter/Dart
.dart_tool/
.packages
build/
.flutter-plugins
.flutter-plugins-dependencies
*.iml

# IDE
.idea/
.vscode/
*.swp

# Android
android/.gradle/
android/local.properties
android/**/GeneratedPluginRegistrant.java

# iOS
ios/Pods/
ios/.symlinks/
ios/**/GeneratedPluginRegistrant.*

# macOS
macos/Flutter/GeneratedPluginRegistrant.swift

# Windows
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugin_registrant.h

# Linux
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugin_registrant.h

# OS
.DS_Store
Thumbs.db
`;

    // 7. Makefile
    files['Makefile'] = `FLUTTER := flutter

.PHONY: run build test analyze clean

run:
\t$(FLUTTER) run

build:
\t$(FLUTTER) build

test:
\t$(FLUTTER) test

analyze:
\t$(FLUTTER) analyze

clean:
\t$(FLUTTER) clean

get:
\t$(FLUTTER) pub get
`;
  },
};
