/**
 * Qt Desktop Strategy
 *
 * Generates C++ Qt desktop applications with CMake.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Qt desktop app strategy
 */
export const QtStrategy: GenerationStrategy = {
  id: 'desktop-qt',
  name: 'Qt Desktop App',
  priority: 10,

  matches: stack =>
    stack.archetype === 'desktop' && stack.language === 'cpp' && stack.framework === 'qt',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/-/g, '_');

    // 1. CMakeLists.txt
    files['CMakeLists.txt'] = `cmake_minimum_required(VERSION 3.20)
project(${cleanName} VERSION 0.1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

find_package(Qt6 REQUIRED COMPONENTS Widgets)

add_executable(${cleanName}
    src/main.cpp
    src/mainwindow.cpp
    src/mainwindow.h
    resources/resources.qrc
)

target_link_libraries(${cleanName} PRIVATE Qt6::Widgets)

install(TARGETS ${cleanName}
    BUNDLE DESTINATION .
    LIBRARY DESTINATION \${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION \${CMAKE_INSTALL_BINDIR}
)
`;

    // 2. main.cpp
    files['src/main.cpp'] = `#include <QApplication>
#include "mainwindow.h"

int main(int argc, char *argv[]) {
    QApplication app(argc, argv);
    app.setApplicationName("${projectName}");
    app.setApplicationVersion("0.1.0");

    MainWindow window;
    window.show();

    return app.exec();
}
`;

    // 3. mainwindow.h
    files['src/mainwindow.h'] = `#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QLabel>
#include <QPushButton>

class MainWindow : public QMainWindow {
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow() override = default;

private slots:
    void onButtonClicked();

private:
    QLabel *m_label;
    int m_counter = 0;
};

#endif // MAINWINDOW_H
`;

    // 4. mainwindow.cpp
    files['src/mainwindow.cpp'] = `#include "mainwindow.h"
#include <QVBoxLayout>
#include <QWidget>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent) {
    setWindowTitle("${projectName}");
    resize(900, 670);

    auto *centralWidget = new QWidget(this);
    auto *layout = new QVBoxLayout(centralWidget);
    layout->setAlignment(Qt::AlignCenter);

    auto *titleLabel = new QLabel("Welcome to ${projectName}!", this);
    titleLabel->setAlignment(Qt::AlignCenter);
    QFont titleFont = titleLabel->font();
    titleFont.setPointSize(24);
    titleFont.setBold(true);
    titleLabel->setFont(titleFont);
    layout->addWidget(titleLabel);

    auto *subtitleLabel = new QLabel("Generated by Retro Vibecoder UPG", this);
    subtitleLabel->setAlignment(Qt::AlignCenter);
    layout->addWidget(subtitleLabel);

    layout->addSpacing(20);

    m_label = new QLabel("Counter: 0", this);
    m_label->setAlignment(Qt::AlignCenter);
    QFont counterFont = m_label->font();
    counterFont.setPointSize(18);
    m_label->setFont(counterFont);
    layout->addWidget(m_label);

    layout->addSpacing(10);

    auto *button = new QPushButton("Increment", this);
    button->setFixedWidth(200);
    layout->addWidget(button, 0, Qt::AlignCenter);
    connect(button, &QPushButton::clicked, this, &MainWindow::onButtonClicked);

    setCentralWidget(centralWidget);
}

void MainWindow::onButtonClicked() {
    m_counter++;
    m_label->setText(QString("Counter: %1").arg(m_counter));
}
`;

    // 5. Resources
    files['resources/resources.qrc'] = `<RCC>
    <qresource prefix="/">
    </qresource>
</RCC>
`;

    // 6. .gitignore
    files['.gitignore'] = `# Build
build/
cmake-build-*/
CMakeFiles/
CMakeCache.txt
cmake_install.cmake
Makefile

# Compiled
*.o
*.obj
*.exe
*.app
*.dylib
*.so
*.dll
moc_*
ui_*
qrc_*

# IDE
.idea/
.vscode/
*.user
*.pro.user*
.qmake.stash

# OS
.DS_Store
Thumbs.db
`;

    // 7. Makefile
    files['Makefile'] = `BUILD_DIR := build

.PHONY: configure build run test clean

configure:
\tcmake -B $(BUILD_DIR) -DCMAKE_BUILD_TYPE=Debug

build: configure
\tcmake --build $(BUILD_DIR)

run: build
\t./$(BUILD_DIR)/${cleanName}

clean:
\trm -rf $(BUILD_DIR)
`;
  },
};
