/**
 * Tauri Desktop Strategy
 *
 * Generates Tauri desktop applications with a TypeScript frontend and Rust backend.
 */

import type { GenerationStrategy } from '../../types.js';

/**
 * Tauri desktop app strategy
 */
export const TauriStrategy: GenerationStrategy = {
  id: 'desktop-tauri',
  name: 'Tauri Desktop App',
  priority: 10,

  matches: stack =>
    stack.archetype === 'desktop' &&
    (stack.language === 'rust' || stack.language === 'typescript') &&
    stack.framework === 'tauri',

  apply: async ({ files, projectName }) => {
    const cleanName = projectName.replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();
    const snakeName = cleanName.replace(/-/g, '_');

    // === Frontend (TypeScript/Vite) ===

    // 1. package.json
    files['package.json'] = JSON.stringify(
      {
        name: cleanName,
        version: '0.1.0',
        description: `${projectName} - Tauri desktop app`,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          'tauri:dev': 'tauri dev',
          'tauri:build': 'tauri build',
        },
        dependencies: {},
        devDependencies: {
          '@tauri-apps/cli': '^2.0.0',
          typescript: '^5.3.0',
          vite: '^5.1.0',
        },
      },
      null,
      2
    );

    // 2. tsconfig.json
    files['tsconfig.json'] = JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: 'dist',
        },
        include: ['src'],
      },
      null,
      2
    );

    // 3. vite.config.ts
    files['vite.config.ts'] = `import { defineConfig } from 'vite';

export default defineConfig({
  clearScreen: false,
  server: {
    port: 1420,
    strictPort: true,
  },
  envPrefix: ['VITE_', 'TAURI_'],
  build: {
    target: ['es2021', 'chrome100', 'safari13'],
    minify: !process.env.TAURI_DEBUG ? 'esbuild' : false,
    sourcemap: !!process.env.TAURI_DEBUG,
  },
});
`;

    // 4. Frontend index.html
    files['index.html'] = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName}</title>
  <link rel="stylesheet" href="/src/styles.css" />
</head>
<body>
  <div id="app">
    <h1>Welcome to ${projectName}!</h1>
    <p>Generated by Retro Vibecoder UPG</p>
    <p id="greet-msg"></p>
    <form id="greet-form">
      <input id="greet-input" placeholder="Enter a name..." />
      <button type="submit">Greet</button>
    </form>
  </div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
`;

    // 5. Frontend main.ts
    files['src/main.ts'] = `const { invoke } = window.__TAURI__.core;

async function greet(): Promise<void> {
  const inputEl = document.querySelector('#greet-input') as HTMLInputElement;
  const msgEl = document.querySelector('#greet-msg');
  if (inputEl && msgEl) {
    const response = await invoke('greet', { name: inputEl.value });
    msgEl.textContent = response as string;
  }
}

window.addEventListener('DOMContentLoaded', () => {
  const form = document.querySelector('#greet-form');
  form?.addEventListener('submit', (e) => {
    e.preventDefault();
    greet();
  });
});
`;

    // 6. Frontend styles
    files['src/styles.css'] = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background-color: #1e1e2e;
  color: #cdd6f4;
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
}

#app {
  text-align: center;
  padding: 2rem;
}

h1 {
  font-size: 2rem;
  margin-bottom: 0.5rem;
  color: #89b4fa;
}

p {
  color: #a6adc8;
  margin-bottom: 1rem;
}

form {
  display: flex;
  gap: 0.5rem;
  justify-content: center;
}

input {
  padding: 0.5rem;
  border: 1px solid #45475a;
  border-radius: 4px;
  background: #313244;
  color: #cdd6f4;
  font-size: 1rem;
}

button {
  padding: 0.5rem 1rem;
  border: none;
  border-radius: 4px;
  background: #89b4fa;
  color: #1e1e2e;
  font-size: 1rem;
  cursor: pointer;
}

button:hover {
  background: #74c7ec;
}
`;

    // === Tauri Backend (Rust) ===

    // 7. Cargo.toml
    files['src-tauri/Cargo.toml'] = `[package]
name = "${snakeName}"
version = "0.1.0"
edition = "2021"

[lib]
name = "${snakeName}_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;

    // 8. tauri.conf.json
    files['src-tauri/tauri.conf.json'] = JSON.stringify(
      {
        $schema: '../node_modules/@tauri-apps/cli/config.schema.json',
        productName: projectName,
        version: '0.1.0',
        identifier: `com.example.${cleanName}`,
        build: {
          beforeDevCommand: 'npm run dev',
          beforeBuildCommand: 'npm run build',
          devUrl: 'http://localhost:1420',
          frontendDist: '../dist',
        },
        app: {
          windows: [
            {
              title: projectName,
              width: 900,
              height: 670,
            },
          ],
        },
      },
      null,
      2
    );

    // 9. Rust main.rs
    files['src-tauri/src/main.rs'] =
      `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

fn main() {
    ${snakeName}_lib::run();
}
`;

    // 10. Rust lib.rs
    files['src-tauri/src/lib.rs'] = `#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
`;

    // 11. build.rs
    files['src-tauri/build.rs'] = `fn main() {
    tauri_build::build();
}
`;

    // 12. .gitignore
    files['.gitignore'] = `node_modules/
dist/
src-tauri/target/
*.tsbuildinfo
.env
.env.local
`;

    // 13. Makefile
    files['Makefile'] = `NPM := npm

.PHONY: dev build tauri-dev tauri-build clean

dev:
\t$(NPM) run dev

build:
\t$(NPM) run build

tauri-dev:
\t$(NPM) run tauri:dev

tauri-build:
\t$(NPM) run tauri:build

clean:
\trm -rf dist node_modules src-tauri/target
`;
  },
};
